import type { ThemeConfig } from '@mindfiredigital/ignix-ui';

export const dyslexiaFriendlyWarmTheme: ThemeConfig = {
  id: 'dyslexia-friendly-warm',
  name: 'Dyslexia-Friendly Warm',
  category: 'accessibility-first',
  description:
    'Warm-toned theme optimized for dyslexic users with strong differentiation.',
  colors: {
    primary: '#E07A5F',
    primaryHover: '#F2CC8F',
    primaryActive: '#D35D38',
    secondary: '#81B29A',
    secondaryHover: '#A8CDB8',
    secondaryActive: '#4E8C73',
    accent: '#F4A261',
    accentHover: '#E9C46A',
    accentActive: '#2A9D8F',
    background: '#F4F1DE',
    backgroundAlt: '#EAE3C9',
    surface: '#FAF3E0',
    surfaceAlt: '#F5E9C9',
    text: '#3D405B',
    textSecondary: '#5C5470',
    textMuted: '#7D7A87',
    textInverse: '#FFFFFF',
    border: '#DDD0B6',
    borderLight: '#E6D9BE',
    borderHover: '#C9BA9C',
    success: '#81B29A',
    warning: '#F4A261',
    error: '#E07A5F',
    info: '#3D405B',
  },
  dark: {
    primary: '#F2CC8F',
    primaryHover: '#E07A5F',
    primaryActive: '#D35D38',
    secondary: '#A8CDB8',
    secondaryHover: '#81B29A',
    secondaryActive: '#4E8C73',
    accent: '#E9C46A',
    accentHover: '#F4A261',
    accentActive: '#2A9D8F',
    background: '#3D3B36',
    backgroundAlt: '#2A2A26',
    surface: '#2F2D2A',
    surfaceAlt: '#24221F',
    text: '#F4F1DE',
    textSecondary: '#DDD0B6',
    textMuted: '#BDB7A4',
    textInverse: '#3D405B',
    border: '#5C5470',
    borderLight: '#7D7A87',
    borderHover: '#9C988F',
    success: '#81B29A',
    warning: '#F4A261',
    error: '#E07A5F',
    info: '#F4F1DE',
  },
  metadata: {
    accessibility: 'AA',
    contrastRatio: 5.2,
    mood: ['friendly', 'comforting', 'approachable'],
    tags: ['dyslexia', 'warm', 'inclusive'],
    industry: ['education', 'health', 'publishing'],
    author: 'Ignix UI Team',
    version: '1.0.0',
  },
};
