import type { ThemeConfig } from '@mindfiredigital/ignix-ui';

export const springBlossomTheme: ThemeConfig = {
  id: 'spring-blossom',
  name: 'Spring Blossom',
  category: 'seasonal',
  description: 'Cheerful spring palette with cherry pink and fresh leaf green.',
  colors: {
    primary: '#FF69B4',
    primaryHover: '#FF85C1',
    primaryActive: '#E91E63',
    secondary: '#32CD32',
    secondaryHover: '#4CAF50',
    secondaryActive: '#228B22',
    accent: '#FFC0CB',
    accentHover: '#FFB6C1',
    accentActive: '#FF69B4',
    background: '#FFF0F5',
    backgroundAlt: '#FFE4E1',
    surface: '#FFFFFF',
    surfaceAlt: '#FFF5F5',
    text: '#212121',
    textSecondary: '#424242',
    textMuted: '#757575',
    textInverse: '#FFFFFF',
    border: '#E0E0E0',
    borderLight: '#F5F5F5',
    borderHover: '#CCCCCC',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  dark: {
    primary: '#FF85C1',
    primaryHover: '#FF69B4',
    primaryActive: '#E91E63',
    secondary: '#4CAF50',
    secondaryHover: '#32CD32',
    secondaryActive: '#228B22',
    accent: '#FFB6C1',
    accentHover: '#FFC0CB',
    accentActive: '#FF69B4',
    background: '#1A0A0A',
    backgroundAlt: '#220F0F',
    surface: '#1A1A1A',
    surfaceAlt: '#222222',
    text: '#FFFFFF',
    textSecondary: '#CCCCCC',
    textMuted: '#999999',
    textInverse: '#212121',
    border: '#555555',
    borderLight: '#666666',
    borderHover: '#777777',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  metadata: {
    accessibility: 'AA',
    contrastRatio: 5.2,
    mood: ['cheerful', 'fresh', 'floral'],
    tags: ['spring', 'blossom', 'pink', 'green'],
    industry: ['design', 'publishing', 'culture'],
    author: 'Ignix UI Team',
    version: '1.0.0',
  },
};
